### ISSUE TITLE
Cannot copy files created by other app

### ISSUE THREAD

**Issue by as564335sa** [Android-for-Python/shared_storage_example#1]
Hi,
I found that on Android 12, it can't copy files created by other apps other than images, but it works under Android 9. What's wrong?

**Comment by Android-for-Python** [comment]
Assuming https://github.com/Android-for-Python/androidstorage4kivy#permissions

Is this using Downloads? see last para here https://github.com/Android-for-Python/androidstorage4kivy#implementation-details  (overly simplistic, but makes the point) 

Other than that I don't know.
