### ISSUE TITLE
Where can I find the Android module listed in the Share_Storage_Example

### ISSUE THREAD

**Issue by steelliberty** [Android-for-Python/shared_storage_example#2]
from android import mActivity, autoclass, api_version

I need help locating the android module.  

Thank you for the help.

**Comment by Android-for-Python** [comment]
The question doesn't say, but I'm guessing this is a platform related, first sentence:
https://github.com/Android-for-Python/Android-for-Python-Users#the-android-package

For general support questions please use https://discord.gg/Dxr6NfSY or https://groups.google.com/g/kivy-users
